{"name": "Tap独家"}
{"name": "单机"}
{"name": "动作"}
{"name": "多人"}
{"name": "模拟经营"}
{"name": "角色扮演"}
{"name": "休闲"}
{"name": "策略"}
{"name": "冒险"}
{"name": "卡牌"}
{"name": "射击"}
{"name": "二次元"}
{"name": "Roguelike"}
{"name": "解谜"}
{"name": "文字"}
{"name": "音游"}
{"name": "女性向"}
{"name": "养成"}
{"name": "沙盒"}
{"name": "开放世界"}
{"name": "MMORPG"}
{"name": "武侠"}
{"name": "国风"}
{"name": "竞速"}
{"name": "益智"}
{"name": "Steam移植"}
{"name": "UP主推荐"}
{"name": "生存"}
{"name": "MOBA"}
{"name": "放置"}
{"name": "塔防"}
{"name": "像素"}
{"name": "治愈"}
{"name": "末日"}
{"name": "格斗"}
{"name": "魔性"}