{"name": "鸣潮", "stat": "9.0"}
{"name": "绝区零", "stat": "8.7"}
{"name": "以闪亮之名", "stat": "8.4"}
{"name": "暗区突围", "stat": "8.3"}
{"name": "纸嫁衣4", "stat": "9.8"}
{"name": "永劫无间手游", "stat": "9.1"}
{"name": "心动小镇", "stat": "9.2"}
{"name": "环形战争", "stat": "8.9"}
{"name": "重返未来：1999", "stat": "9.1"}
{"name": "火炬之光：无限", "stat": "8.5"}
{"name": "龙与世界的尽头", "stat": "7.9"}
{"name": "崩坏：星穹铁道", "stat": "8.1"}
{"name": "未来之役", "stat": "8.2"}
{"name": "猫之城", "stat": "8.4"}
{"name": "元气骑士新作", "stat": "9.0"}
{"name": "明日方舟：终末地", "stat": "9.2"}
{"name": "黎明前20分钟", "stat": "9.3"}
{"name": "魂", "stat": "9.5"}
{"name": "逆水寒", "stat": "8.6"}
{"name": "跃迁旅人", "stat": "8.7"}
{"name": "霓虹深渊：无限", "stat": "9.6"}
{"name": "名画展", "stat": "10"}
{"name": "无期迷途", "stat": "8.1"}
{"name": "奥西里之环", "stat": "8.5"}
{"name": "代号·花神", "stat": "8.3"}
{"name": "代号：降临", "stat": "8.7"}
{"name": "小小蚁国", "stat": "9.6"}
{"name": "模拟农场20", "stat": "8.4"}
{"name": "暗黑破坏神：不朽", "stat": "6.4"}
{"name": "异侠传：道消魔长", "stat": "9.8"}
{"name": "PuffPals: Island Skies", "stat": "9.3"}
{"name": "璀璨之旅", "stat": "8.6"}
{"name": "2089：边境", "stat": "8.8"}
{"name": "Desta: The Memories Between", "stat": "9.2"}
{"name": "末日的第53天", "stat": "9.2"}
{"name": "流浪方舟", "stat": "9.0"}
{"name": "时空猎人3", "stat": "6.6"}
{"name": "星火之歌", "stat": "7.7"}
{"name": "DuDu", "stat": "9.8"}
{"name": "尘白禁区", "stat": "9.2"}
{"name": "黑暗笔录", "stat": "9.9"}
{"name": "画中世界", "stat": "9.9"}
{"name": "不良人3", "stat": "8.1"}
{"name": "方舟：生存进化", "stat": "7.5"}
{"name": "雾起谜踪", "stat": "9.3"}
{"name": "铃兰之剑：为这和平的世界", "stat": "9.1"}
{"name": "空蝉", "stat": "9.9"}
{"name": "汪汪露营会", "stat": "9.1"}
{"name": "二分之一", "stat": "8.8"}
{"name": "螺旋勇士", "stat": "9.1"}
{"name": "雷索纳斯", "stat": "8.3"}
{"name": "黎明觉醒", "stat": "8.0"}
{"name": "彩虹六号M", "stat": "6.1"}
{"name": "星际战甲Warframe手游", "stat": "9.5"}
{"name": "来自星尘", "stat": "8.2"}
{"name": "逐鹿", "stat": "9.3"}
{"name": "行界：重构", "stat": "8.9"}
{"name": "火环", "stat": "9.7"}
{"name": "超自然侦探社", "stat": "9.6"}
{"name": "萌宠物语", "stat": "9.5"}
{"name": "混沌效应", "stat": "9.3"}
{"name": "Project M", "stat": "4.2"}
{"name": "战地手游", "stat": "7.0"}
{"name": "CoA", "stat": "9.0"}
{"name": "锚点降临", "stat": "8.5"}
{"name": "Project 24/36", "stat": "8.8"}
{"name": "幽灵事务所2：查利", "stat": "10"}
{"name": "大多数", "stat": "7.8"}
{"name": "逆光潜入", "stat": "8.6"}
{"name": "无名江湖", "stat": "9.3"}
{"name": "镜地", "stat": "9.2"}
{"name": "魔兽之旅", "stat": "8.7"}
{"name": "搬家模拟器", "stat": "9.5"}
{"name": "世界计划 缤纷舞台！feat. 初音未來", "stat": "9.0"}
{"name": "我的毕业日记", "stat": "9.4"}
{"name": "代号塔防", "stat": "9.5"}
{"name": "我的网红女友：养成计划", "stat": "9.2"}
{"name": "阴阳锅", "stat": "9.4"}
{"name": "代号：蝶", "stat": "9.7"}
{"name": "指尖领主", "stat": "7.9"}
{"name": "0.64平方米的光都与你有关", "stat": "9.9"}
{"name": "少女前线2：追放", "stat": "8.1"}
{"name": "螺旋圆舞曲2蔷薇战争", "stat": "8.7"}
{"name": "晚安森林", "stat": "9.7"}
{"name": "梦幻之城", "stat": "9.6"}
{"name": "传说法师", "stat": "9.6"}
{"name": "ZOZ: Final Hour", "stat": "7.2"}
{"name": "满庭芳·宋上繁华", "stat": "9.6"}
{"name": "波西亚时光", "stat": "9.2"}
{"name": "Draw & Guess（你画我猜）", "stat": "8.5"}
{"name": "拼图小镇物语", "stat": "9.8"}
{"name": "悠闲的小时光", "stat": "9.5"}
{"name": "继承了一座戏园子", "stat": "9.6"}
{"name": "赠予神家与谎言", "stat": "9.7"}
{"name": "乌托邦之血", "stat": "9.7"}
{"name": "星露谷物语", "stat": "4.6"}
{"name": "Orpheus（俄耳甫斯）", "stat": "9.9"}
{"name": "我在异界的开挂人生", "stat": "9.1"}
{"name": "代号：红玄传", "stat": "9.7"}
{"name": "白荆回廊", "stat": "9.5"}
{"name": "我亲爱的农场", "stat": "8.3"}
{"name": "吸血鬼幸存者（Vampire Survivors）", "stat": "8.6"}
{"name": "猫猫蛇MOMOS", "stat": "9.7"}
{"name": "像素世界岛-安体", "stat": "9.3"}
{"name": "迷失星球", "stat": "9.1"}
{"name": "代号：GFG", "stat": "8.6"}
{"name": "生死狙击2", "stat": "8.2"}
{"name": "这城有点田", "stat": "9.2"}
{"name": "心渊梦境", "stat": "9.2"}
{"name": "ACE虚拟歌姬", "stat": "9.3"}
{"name": "代号：Spark", "stat": "8.6"}
{"name": "战争公约", "stat": "8.3"}
{"name": "萤火突击", "stat": "6.8"}
{"name": "保卫萝卜4", "stat": "7.9"}
{"name": "魔力宝贝：旅人", "stat": "7.8"}
{"name": "代号A", "stat": "9.1"}
{"name": "再刷一把", "stat": "9.8"}
{"name": "海岛世界", "stat": "9.0"}
{"name": "小生活", "stat": "9.7"}
{"name": "宿命回响", "stat": "8.2"}
{"name": "枕边故事", "stat": "9.9"}
{"name": "代号：了不起的模拟器", "stat": "9.0"}
{"name": "暂时还没想好名字的肉鸽战棋", "stat": "9.5"}
{"name": "抽屉里的秘密", "stat": "9.5"}
{"name": "灵魂摆渡人", "stat": "9.8"}
{"name": "残花葬", "stat": "9.6"}
{"name": "腾讯游戏发布会", "stat": "8.2"}
{"name": "异次元冲刺", "stat": "7.8"}
{"name": "代号：艾塔", "stat": "8.6"}
{"name": "泪水与晚安", "stat": "10"}
{"name": "爱与荒野", "stat": "9.5"}
{"name": "破烂水手", "stat": "8.5"}
{"name": "双生怨", "stat": "9.2"}
{"name": "怪兽星球2", "stat": "9.3"}
{"name": "妖刀退魔忍", "stat": "8.7"}
{"name": "Cartesian", "stat": "9.7"}
{"name": "武义九州", "stat": "9.7"}
{"name": "哦！又上头条了", "stat": "9.8"}
{"name": "咏月风雅", "stat": "8.3"}
{"name": "代号：双月", "stat": "9.3"}
{"name": "双相", "stat": "9.8"}
{"name": "假未来Fake Future", "stat": "9.3"}
{"name": "逆位时间", "stat": "9.8"}
{"name": "钢铁战队：入侵", "stat": "9.6"}
{"name": "神仙道3", "stat": "8.2"}
{"name": "美食大乱斗", "stat": "8.4"}
{"name": "超级工厂模拟器", "stat": "9.2"}
{"name": "Wild Arena Survivors", "stat": "7.4"}
{"name": "旅人苏菲亚", "stat": "9.8"}
